version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - habit-tracker-network

  quarkus:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - habit-tracker-network

networks:
  habit-tracker-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local